import type { Executive } from "./types";

export const months = ["January", "February", "March", "April", "May", "June"];

export const executives: Executive[] = [
  {
    id: 1,
    name: "Naveen Kumar",
    staffId: "ID - 274292",
    role: "Infrastructure Executive",
    category: "Infrastructure",
    image: "/w-e-m.png",
    phone: "+91 90847 46247",
    email: "naveenkumar@gmail.com",
    status: "Actively Contributing",
    totalIssues: 52,
    resolvedIssues: 44,
    contribution: 34,
    issues: [
      {
        id: "R-1",
        title: "Projector not working in CR - 2",
        category: "Infrastructure",
        priority: "Urgent",
        date: "03/27/2026",
        description:
          "The projector in Classroom CR-2 is not working and is unable to display content during lectures. Faculty tried reconnecting the cables and restarting the system, but the issue still persists. This is affecting ongoing classes, so maintenance support is required as soon as possible.",
        attachments: [
          { name: "Project_error.jpg", size: "60 KB" },
          { name: "Project_error.jpg2", size: "60 KB" },
        ],
      },
      {
        id: "R-2",
        title: "AC cooling issue in Faculty Room 3",
        category: "Infrastructure",
        priority: "High",
        date: "03/28/2026",
        description:
          "The air conditioning unit is making a loud noise and not cooling effectively. Multiple faculty members have reported discomfort and require technician support.",
        attachments: [{ name: "AC_Unit_Panel.jpg", size: "1.2 MB" }],
      },
    ],
  },
  {
    id: 2,
    name: "Habeeba Nazeer",
    staffId: "ID - 274292",
    role: "Hostel Executive",
    category: "Hostel",
    image: "/w-e-f.png",
    phone: "+91 90123 46247",
    email: "habeeba.nazeer@gmail.com",
    status: "Actively Contributing",
    totalIssues: 47,
    resolvedIssues: 39,
    contribution: 29,
    issues: [
      {
        id: "R-3",
        title: "WiFi not working in Hostel Floor 3",
        category: "Hostel",
        priority: "Urgent",
        date: "03/29/2026",
        description:
          "Students reported poor connectivity on the third floor. The router needs checking and signal coverage may need to be improved.",
        attachments: [{ name: "Wifi_signal.jpg", size: "80 KB" }],
      },
    ],
  },
  {
    id: 3,
    name: "Sachin Dantala",
    staffId: "ID - 274292",
    role: "Sports Executive",
    category: "Sports",
    image: "/admin-m.png",
    phone: "+91 90987 46247",
    email: "sachin.dantala@gmail.com",
    status: "Monitoring",
    totalIssues: 38,
    resolvedIssues: 27,
    contribution: 21,
    issues: [
      {
        id: "R-4",
        title: "Ground maintenance required",
        category: "Sports",
        priority: "High",
        date: "03/30/2026",
        description:
          "Football field has uneven patches and requires ground staff inspection before practice sessions continue.",
        attachments: [{ name: "Ground_report.jpg", size: "90 KB" }],
      },
    ],
  },
  {
    id: 4,
    name: "Manav Rajput",
    staffId: "ID - 274292",
    role: "Infrastructure Executive",
    category: "Infrastructure",
    image: "/student-m.png",
    phone: "+91 90847 40011",
    email: "manav.rajput@gmail.com",
    status: "Actively Contributing",
    totalIssues: 33,
    resolvedIssues: 24,
    contribution: 19,
    issues: [],
  },
  {
    id: 5,
    name: "Zoha Sadaf",
    staffId: "ID - 274292",
    role: "Medical Executive",
    category: "Medical",
    image: "/w-m-f.png",
    phone: "+91 90847 40012",
    email: "zoha.sadaf@gmail.com",
    status: "Monitoring",
    totalIssues: 29,
    resolvedIssues: 21,
    contribution: 16,
    issues: [],
  },
];
