import {
  Article,
  ChartBar,
  Confetti,
  Circuitry,
  Desktop,
  Globe,
  GridFour,
  Money,
  OfficeChair,
  Receipt,
  Wallet,
  Wrench,
} from "@phosphor-icons/react";

export const expenseSummaryCards = [
  {
    label: "Total Expenses",
    value: "Rs 2.84 Cr",
    detail: "All time",
    icon: Wallet,
    iconBg: "bg-[#DDF8E9]",
    iconBgColor: "#43C17A",
    iconColor: "#35C77A",
  },
  {
    label: "This Month Spending",
    value: "Rs 18.45 L",
    detail: "May 2025",
    icon: ChartBar,
    iconBg: "bg-[#E1ECFF]",
    iconBgColor: "#3F7DF4",
    iconColor: "#4B7DFF",
  },
  {
    label: "Expense Categories",
    value: "12",
    detail: "Active Categories",
    icon: GridFour,
    iconBg: "bg-[#EEE1FF]",
    iconBgColor: "#A64FF2",
    iconColor: "#9B4DFF",
  },
  {
    label: "Transactions Recorded",
    value: "1,248",
    detail: "All time",
    icon: Article,
    iconBg: "bg-[#FFE8D3]",
    iconBgColor: "#FF9238",
    iconColor: "#FF9238",
  },
];

export const monthlyExpenseData = [
  { month: "Jan", value: 13 },
  { month: "Feb", value: 20 },
  { month: "Mar", value: 17 },
  { month: "Apr", value: 23 },
  { month: "May", value: 31 },
  { month: "Jun", value: 26 },
  { month: "Jul", value: 13 },
  { month: "Aug", value: 20 },
  { month: "Sep", value: 23 },
  { month: "Oct", value: 17 },
  { month: "Nov", value: 13 },
  { month: "Dec", value: 20 },
];

export const expenseCategories = [
  {
    title: "Salaries",
    countLabel: "Employees Paid",
    count: "246",
    amount: "Rs 18.50 L",
    bg: "bg-[#DFFBEA]",
    icon: Money,
    color: "#16B96F",
  },
  {
    title: "Events",
    countLabel: "Events Conducted",
    count: "8",
    amount: "Rs 4.20 L",
    bg: "bg-[#EFE4FF]",
    icon: Confetti,
    color: "#8B4DFF",
  },
  {
    title: "Furniture",
    countLabel: "Assets Purchased",
    count: "32",
    amount: "Rs 2.80 L",
    bg: "bg-[#FFEBD6]",
    icon: OfficeChair,
    color: "#FF8A2A",
  },
  {
    title: "Internet & Network",
    countLabel: "Active Services",
    count: "6",
    amount: "Rs 1.20 L",
    bg: "bg-[#E3F0FF]",
    icon: Globe,
    color: "#4A82FF",
  },
  {
    title: "Software & Subscriptions",
    countLabel: "Active Licenses",
    count: "24",
    amount: "Rs 3.50 L",
    bg: "bg-[#E2FAF0]",
    icon: Desktop,
    color: "#0FAE78",
  },
  {
    title: "Infrastructure",
    countLabel: "Active Projects",
    count: "7",
    amount: "Rs 12.80 L",
    bg: "bg-[#FFE9F1]",
    icon: Wrench,
    color: "#FF477E",
  },
  {
    title: "Utilities",
    countLabel: "Bills Recorded",
    count: "15",
    amount: "Rs 1.90 L",
    bg: "bg-[#FFF3D2]",
    icon: Circuitry,
    color: "#E0A300",
  },
];

export const recentExpenseRecords = [
  {
    title: "Faculty Salary",
    subtitle: "Salaries",
    date: "23 Oct 2025",
    amount: "Rs 2,10,000",
    icon: Money,
    bg: "bg-[#DFFBEA]",
    color: "#16B96F",
  },
  {
    title: "Annual Day Event",
    subtitle: "Events",
    date: "22 Oct 2025",
    amount: "Rs 75,000",
    icon: Confetti,
    bg: "bg-[#EFE4FF]",
    color: "#8B4DFF",
  },
  {
    title: "Office Chairs Purchase",
    subtitle: "Furniture",
    date: "21 Oct 2025",
    amount: "Rs 45,600",
    icon: OfficeChair,
    bg: "bg-[#FFEBD6]",
    color: "#FF8A2A",
  },
  {
    title: "Internet Connection",
    subtitle: "Internet & Network",
    date: "20 Oct 2025",
    amount: "Rs 12,500",
    icon: Globe,
    bg: "bg-[#E3F0FF]",
    color: "#4A82FF",
  },
  {
    title: "Software Subscription",
    subtitle: "Software & Subscriptions",
    date: "19 Oct 2025",
    amount: "Rs 28,000",
    icon: Desktop,
    bg: "bg-[#E2FAF0]",
    color: "#0FAE78",
  },
  {
    title: "Faculty Salary",
    subtitle: "Salaries",
    date: "23 Oct 2025",
    amount: "Rs 2,10,000",
    icon: Money,
    bg: "bg-[#DFFBEA]",
    color: "#16B96F",
  },
  {
    title: "Annual Day Event",
    subtitle: "Events",
    date: "22 Oct 2025",
    amount: "Rs 75,000",
    icon: Confetti,
    bg: "bg-[#EFE4FF]",
    color: "#8B4DFF",
  },
];

export const totalExpenseStats = [
  {
    label: "Total Expenses",
    value: "Rs 2.84 Cr",
    icon: Wallet,
    iconBgColor: "#43C17A",
    iconColor: "#FFFFFF",
  },
  {
    label: "This Month",
    value: "Rs 18.45 L",
    icon: ChartBar,
    iconBgColor: "#E4F2EA",
    iconColor: "#43C17A",
  },
  {
    label: "Total Records",
    value: "1,248",
    icon: Article,
    iconBgColor: "#E4F2EA",
    iconColor: "#43C17A",
  },
  {
    label: "Categories",
    value: "12",
    icon: GridFour,
    iconBgColor: "#E4F2EA",
    iconColor: "#43C17A",
  },
];

export const totalExpenseRecords = [
  {
    expenseId: "EXP001",
    category: "Salaries",
    categoryTone: "green",
    expenseName: "Faculty Salary - October",
    amount: "Rs 2,10,000",
    date: "23 Oct 2025",
  },
  {
    expenseId: "EXP002",
    category: "Events",
    categoryTone: "pink",
    expenseName: "Annual Day Event",
    amount: "Rs 75,000",
    date: "22 Oct 2025",
  },
  {
    expenseId: "EXP003",
    category: "Furniture",
    categoryTone: "pink",
    expenseName: "Office Chairs Purchase",
    amount: "Rs 45,600",
    date: "21 Oct 2025",
  },
  {
    expenseId: "EXP004",
    category: "Software",
    categoryTone: "green",
    expenseName: "Cloud Service Subscription",
    amount: "Rs 12,400",
    date: "20 Oct 2025",
  },
];

export const thisMonthCategorySpending = [
  {
    title: "Salaries",
    amount: "Rs 8.2 L",
    icon: Money,
    bg: "bg-[#EFEFEF]",
    iconBg: "#DDF8E9",
    color: "#086C20",
  },
  {
    title: "Infrastructure",
    amount: "Rs 4.5 L",
    icon: Wrench,
    bg: "bg-[#EFEFEF]",
    iconBg: "#E4F2EA",
    color: "#0A4C8F",
  },
  {
    title: "Internet & Network",
    amount: "Rs 80,000",
    icon: Globe,
    bg: "bg-[#EFEFEF]",
    iconBg: "#EAF7F8",
    color: "#063D5E",
  },
  {
    title: "Utilities",
    amount: "Rs 65,000",
    icon: Circuitry,
    bg: "bg-[#EFEFEF]",
    iconBg: "#FFF8D8",
    color: "#7A3300",
  },
  {
    title: "Events",
    amount: "Rs 2.1 L",
    icon: Confetti,
    bg: "bg-[#EFEFEF]",
    iconBg: "#F8F0FF",
    color: "#5F169A",
  },
];

export const thisMonthExpenseRecords = [
  {
    date: "23 Oct",
    category: "Salaries",
    categoryTone: "green",
    expenseName: "Faculty Salary",
    amount: "Rs 2,10,000",
  },
  {
    date: "22 Oct",
    category: "Events",
    categoryTone: "green",
    expenseName: "Annual Day Event",
    amount: "Rs 75,000",
  },
  {
    date: "21 Oct",
    category: "Infrastructure",
    categoryTone: "gray",
    expenseName: "Office Chairs",
    amount: "Rs 45,600",
  },
  {
    date: "19 Oct",
    category: "Internet",
    categoryTone: "blue",
    expenseName: "Bandwidth Renewal",
    amount: "Rs 8,400",
  },
];

export const weeklySpendingTrend = [
  { week: "Week 1", amount: 28, displayAmount: "Rs 2.8L" },
  { week: "Week 2", amount: 42, displayAmount: "Rs 4.2L" },
  { week: "Week 3", amount: 35, displayAmount: "Rs 3.5L" },
  { week: "Week 4", amount: 63.5, displayAmount: "Rs 6.35L" },
];
