import { CheckCircle, ListChecks, Siren, Warning } from "@phosphor-icons/react";
import type { CategoryIssue } from "./types";

export const issueRows: CategoryIssue[] = [
  {
    id: "CAT-1",
    student: "Ankitha Sharma",
    meta: "B.Tech CSE  |  ID-28939",
    image: "/female-student.png",
    title: "Projector not working in CR-2",
    description: "The project has not been working since morning.",
    category: "Infrastructure",
    priority: "Medium",
    block: "A",
    room: "A-206",
    evidence: "projector-evidence.pdf",
  },
  {
    id: "CAT-2",
    student: "Shreya Patel",
    meta: "B.Tech CSE  |  ID-28939",
    image: "/student-m.png",
    title: "WiFi not working in Hostel Floor 3",
    description: "Internet connectivity is very poor or unavailable.",
    category: "Infrastructure",
    priority: "Medium",
    block: "B",
    room: "A-205",
    evidence: "hostel-wifi.pdf",
  },
  {
    id: "CAT-3",
    student: "Rahul Sharma",
    meta: "B.Tech CSE  |  ID-28939",
    image: "/rahul.png",
    title: "Noise disturbance at night",
    description: "Students in nearby classes are making noise.",
    category: "Infrastructure",
    priority: "Medium",
    block: "A",
    room: "A-203",
    evidence: "noise-report.pdf",
  },
  {
    id: "CAT-4",
    student: "Priya Sharma",
    meta: "B.Tech CSE  |  ID-28939",
    image: "/female-fe.png",
    title: "Ground maintenance required",
    description: "Football field has uneven surface.",
    category: "Sports",
    priority: "High",
    block: "C",
    room: "B-118",
    evidence: "ground-report.pdf",
  },
  {
    id: "CAT-5",
    student: "Ankitha Sharma",
    meta: "B.Tech CSE  |  ID-28939",
    image: "/female-student.png",
    title: "Projector not working in CR-2",
    description: "The project has not been working since morning.",
    category: "Infrastructure",
    priority: "Medium",
    block: "A",
    room: "A-210",
    evidence: "projector-evidence.pdf",
  },
];

export const statCards = [
  {
    label: "This month Total Issues",
    value: "128",
    icon: ListChecks,
    bg: "bg-[#F0E9FF]",
    iconBg: "bg-[#E6DBFF]",
    iconColor: "text-[#7C3AED]",
  },
  {
    label: "High Priority",
    value: "18",
    icon: Siren,
    bg: "bg-[#FFE8E8]",
    iconBg: "bg-[#FFD7D7]",
    iconColor: "text-[#FF1F1F]",
  },
  {
    label: "Pending",
    value: "32",
    icon: Warning,
    bg: "bg-[#FFF0D9]",
    iconBg: "bg-[#FFE0B3]",
    iconColor: "text-[#F59E0B]",
  },
  {
    label: "Resolved",
    value: "78",
    icon: CheckCircle,
    bg: "bg-[#E3F8EC]",
    iconBg: "bg-[#CFF4E0]",
    iconColor: "text-[#27A966]",
  },
];
