import { JobInfoCardProps } from "./jobInfoCard";

export const jobInfoCardData: JobInfoCardProps[] = [
    {
        companyName: "Infosys",
        role: "Software Engineer",
        appliedOn: new Date().toLocaleDateString("en-GB", {
            day: "2-digit",
            month: "short",
            year: "numeric",
        }),
        statusLabel: "Applied",
        skills: ["Java", "Python", "Data Structures", "SQL"],
        description:
            "Work on designing, coding, and deploying enterprise-grade applications using modern frameworks.",
        jobType: "Full Time",
        location: "Hyderabad",
        ctc: "12 Lpa",
        startDate: "20 Sep 2025",
        endDate: "30 Sep 2025",
        logoUrl: "https://logo.clearbit.com/infosys.com",
    },
    {
        companyName: "Google",
        role: "Software Engineer Intern",
        appliedOn: "12 Sep 2025",
        statusLabel: "Shortlisted",
        skills: ["Go", "Distributed Systems", "Algorithms", "Machine Learning"],
        description: "Build high-performance distributed systems at scale.",
        jobType: "Internship",
        location: "Bangalore",
        ctc: "80k / Month",
        startDate: "12 Sep 2025",
        endDate: "22 Sep 2025",
        logoUrl: "https://logo.clearbit.com/google.com",
    },
    {
        companyName: "TCS",
        role: "Assistant System Engineer",
        appliedOn: "02 Nov 2025",
        statusLabel: "Applied",
        skills: ["Java", "OOP", "Spring Boot", "SQL"],
        description:
            "Work on enterprise application development for global clients.",
        jobType: "Full Time",
        location: "Pune",
        ctc: "7 Lpa",
        startDate: "02 Nov 2025",
        endDate: "12 Nov 2025",
        logoUrl: "https://logo.clearbit.com/tcs.com",
    },
    {
        companyName: "Deloitte",
        role: "Business Technology Analyst",
        appliedOn: "27 Oct 2025",
        statusLabel: "Applied",
        skills: ["Analytics", "SQL", "Cloud Basics", "Testing"],
        description:
            "Analyze business requirements and optimize digital workflows.",
        jobType: "Full Time",
        location: "Gurgaon",
        ctc: "10.5 Lpa",
        startDate: "27 Oct 2025",
        endDate: "06 Nov 2025",
        logoUrl: "https://logo.clearbit.com/deloitte.com",
    },
    {
        companyName: "Accenture",
        role: "Application Development Associate",
        appliedOn: "14 Oct 2025",
        statusLabel: "Shortlisted",
        skills: ["Cloud", "Java", "React", "REST APIs"],
        description: "Develop scalable cloud-native applications.",
        jobType: "Full Time",
        location: "Chennai",
        ctc: "8.5 Lpa",
        startDate: "14 Oct 2025",
        endDate: "24 Oct 2025",
        logoUrl: "https://logo.clearbit.com/accenture.com",
    },
    {
        companyName: "Amazon",
        role: "SDE 1",
        appliedOn: "20 Oct 2025",
        statusLabel: "Applied",
        skills: ["Java", "AWS", "System Design", "DSA"],
        description:
            "Work on high-scale backend systems powering Amazon ecommerce.",
        jobType: "Full Time",
        location: "Bangalore",
        ctc: "22 Lpa",
        startDate: "20 Oct 2025",
        endDate: "30 Oct 2025",
        logoUrl: "https://logo.clearbit.com/amazon.com",
    },
];
