export type StaffAttendanceStatus = "present" | "absent" | "late";

export type StaffAttendanceRecord = {
  id: number;
  staffId: string;
  name: string;
  role: string;
  status: StaffAttendanceStatus;
  designation: string;
  department: string;
  shift: string;
  joiningDate: string;
  reportingTo: string;
  phone: string;
  email: string;
  address: string;
  totalWorkingDays: number;
  presentDays: number;
  absentDays: number;
};

export const staffAttendanceRecords: StaffAttendanceRecord[] = [
  {
    id: 1,
    staffId: "STF1023",
    name: "Aman Sharma",
    role: "Ground Staff",
    status: "present",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "aman.sharma@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 22,
    absentDays: 2,
  },
  {
    id: 2,
    staffId: "STF1024",
    name: "Rahul Kumar",
    role: "Ground Staff",
    status: "present",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "deekshithachatla1@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 22,
    absentDays: 2,
  },
  {
    id: 3,
    staffId: "STF1025",
    name: "Dinesh Kumar",
    role: "Ground Staff",
    status: "absent",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "dinesh.kumar@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 20,
    absentDays: 4,
  },
  {
    id: 4,
    staffId: "STF1026",
    name: "Suresh Jadhav",
    role: "Ground Staff",
    status: "absent",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "suresh.jadhav@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 19,
    absentDays: 5,
  },
  {
    id: 5,
    staffId: "STF1027",
    name: "Manoj Patil",
    role: "Ground Staff",
    status: "late",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "manoj.patil@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 21,
    absentDays: 3,
  },
  {
    id: 6,
    staffId: "STF1028",
    name: "Vijay Kumar",
    role: "Ground Staff",
    status: "present",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "vijay.kumar@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 23,
    absentDays: 1,
  },
  {
    id: 7,
    staffId: "STF1029",
    name: "Kiran Reddy",
    role: "Ground Staff",
    status: "present",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "kiran.reddy@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 22,
    absentDays: 2,
  },
  {
    id: 8,
    staffId: "STF1030",
    name: "Naveen Singh",
    role: "Ground Staff",
    status: "present",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "naveen.singh@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 22,
    absentDays: 2,
  },
  {
    id: 9,
    staffId: "STF1031",
    name: "Harish Gowda",
    role: "Ground Staff",
    status: "absent",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "harish.gowda@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 18,
    absentDays: 6,
  },
  {
    id: 10,
    staffId: "STF1032",
    name: "Ramesh Naik",
    role: "Ground Staff",
    status: "present",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "ramesh.naik@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 22,
    absentDays: 2,
  },
  {
    id: 11,
    staffId: "STF1033",
    name: "Sanjay Das",
    role: "Ground Staff",
    status: "late",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "sanjay.das@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 20,
    absentDays: 4,
  },
  {
    id: 12,
    staffId: "STF1034",
    name: "Arjun Rao",
    role: "Ground Staff",
    status: "present",
    designation: "Ground Keeper",
    department: "Sports",
    shift: "Morning Shift",
    joiningDate: "12 Jan 2024",
    reportingTo: "Sports Executive",
    phone: "+91 XXXXX XXXXX",
    email: "arjun.rao@gmail.com",
    address: "Hyderabad, Telangana",
    totalWorkingDays: 24,
    presentDays: 23,
    absentDays: 1,
  },
];

export const getInitials = (name: string) =>
  name
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
