export interface SearchRoute {
  label: string;
  path: string;
  category: string;
  subLabel?: string;
  keywords?: string[];
}

export const ROLE_BASED_ROUTES: Record<string, SearchRoute[]> = {
  Student: [
    { label: "Home", path: "/stu_dashboard", category: "General", keywords: [] },
    { label: "Calendar", path: "/calendar", category: "General", keywords: ["timetable"] },
    { label: "Attendance", path: "/attendance", category: "Academics", keywords: [] },
    { label: "Assignments", path: "/assignments", category: "Academics", keywords: [] },
    { label: "Assignments", subLabel: "Quiz", path: "/assignments?tab=quiz&quizView=ongoing", category: "Academics", keywords: ["quiz"] },
    { label: "Assignments", subLabel: "Discussion Forum", path: "/assignments?tab=discussion&quizView=ongoing&discussionView=active", category: "Academics", keywords: ["discussion", "forum"] },
    { label: "Academics", path: "/academics", category: "Academics", keywords: [] },
    { label: "Student Progress", path: "/student-progress", category: "Academics", keywords: [] },
    { label: "Projects", path: "/projects", category: "Academics", keywords: [] },
    { label: "Placements", path: "/stu_placements", category: "Career", keywords: ["jobs", "interviews"] },
    { label: "Leave Requests", path: "/leaveRequests", category: "General", keywords: ["leave", "permission"] },
    { label: "Payments", path: "/payments", category: "Finance", keywords: ["fees", "dues", "receipts"] },
    { label: "Club", path: "/clubs", category: "Extracurricular", keywords: ["activities"] },
    { label: "Drive", path: "/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", path: "/meetings", category: "General", keywords: [] },
    { label: "Settings", path: "/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo",] },
    { label: "Resume", path: "/profile?resume=personal-details&Step=1", category: "Career", keywords: ["resume", "cv",] },
  ],
  Faculty: [
    { label: "Home", path: "/faculty", category: "General", keywords: [] },
    { label: "Calendar", path: "/faculty/calendar", category: "General", keywords: ["timetable"] },
    { label: "Attendance", path: "/faculty/attendance", category: "Academics", keywords: [""] },
    { label: "Assignments", path: "/faculty/assignments", category: "Academics", keywords: [] },
    { label: "Assignments", subLabel: "Quiz", path: "/faculty/assignments?tab=quiz&quizView=ongoing", category: "Academics", keywords: ["quiz"] },
    { label: "Assignments", subLabel: "Discussion Forum", path: "/faculty/assignments?tab=discussion&quizView=ongoing&discussionView=active", category: "Academics", keywords: ["discussion", "forum"] },
    { label: "Academics", path: "/faculty/academics", category: "Academics", keywords: [] },
    { label: "Student Progress", path: "/faculty/student-progress", category: "Academics", keywords: [] },
    { label: "Projects", path: "/faculty/projects", category: "Academics", keywords: [] },
    { label: "Placements", path: "/faculty/placements", category: "Career", keywords: ["jobs", "interviews"] },
    { label: "Leave Requests", path: "/faculty/leaveRequests", category: "General", keywords: ["permission",] },
    { label: "Club", path: "/faculty/clubs", category: "Extracurricular", keywords: ["activities"] },
    { label: "Drive", path: "/faculty/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", path: "/faculty/meetings", category: "General", keywords: [] },
    { label: "My Attendance", path: "/faculty/my-attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "Settings", path: "/faculty/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/faculty/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
  Admin: [
    { label: "Home", path: "/admin", category: "General", keywords: [] },
    { label: "Calendar", path: "/admin/calendar", category: "General", keywords: ["timetable"] },
    { label: "Attendance", path: "/admin/attendance", category: "Academics", keywords: [] },
    { label: "Assignments", path: "/admin/assignments", category: "Academics", keywords: [] },
    { label: "Assignments", subLabel: "Quiz", path: "/admin/assignments?tab=quiz&quizView=ongoing", category: "Academics", keywords: ["quiz"] },
    { label: "Assignments", subLabel: "Discussion Forum", path: "/admin/assignments?tab=discussion&quizView=ongoing&discussionView=active", category: "Academics", keywords: ["discussion", "forum"] },
    { label: "Academics", path: "/admin/academics", category: "Academics", keywords: ["curriculum"] },
    { label: "Student Progress", path: "/admin/student-progress", category: "Academics", keywords: ["performance", "reports", "analytics"] },
    { label: "Projects", path: "/admin/projects", category: "Academics", keywords: [] },
    { label: "Academic Setup", path: "/admin/academic-setup", category: "Academics", keywords: ["configuration", "structure", "courses"] },
    { label: "Academic Setup", subLabel: "Add Subject", path: "/admin/academic-setup?", category: "Academics", keywords: ["add subject", "subject add"] },
    { label: "Placements", path: "/admin/placements", category: "Career", keywords: ["drives", "companies"] },
    { label: "Club", path: "/admin/clubs", category: "Extracurricular", keywords: ["management", "organizations"] },
    { label: "Drive", path: "/admin/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", path: "/admin/meetings", category: "General", keywords: [] },
    { label: "My Attendance", path: "/admin/my-attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "Settings", path: "/admin/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/admin/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
  CollegeAdmin: [
    { label: "Home", path: "/college-admin", category: "General", keywords: [] },
    { label: "Institution Management", path: "/college-admin/institution-management", category: "Management", keywords: ["manage", "organization"] },
    { label: "Add Admin", path: "/college-admin/add-admin", category: "Management", keywords: ["new admin", "register", "create admin"] },
    { label: "Calendar", path: "/college-admin/calendar", category: "General", keywords: [] },
    { label: "Drive", path: "/college-admin/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "My Attendance", path: "/college-admin/my-attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "Settings", path: "/college-admin/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/college-admin/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
  CollegeHr: [
    { label: "Home", path: "/hr", category: "General", keywords: [] },
    { label: "Calendar", path: "/hr/calendar", category: "General", keywords: [] },
    { label: "Attendance", path: "/hr/attendance", category: "Management", keywords: ["staff attendance"] },
    { label: "Placements", path: "/hr/placements", category: "Career", keywords: ["jobs", "interviews", "companies", "recruitment"] },
    { label: "Drive", path: "/hr/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", path: "/hr/meetings", category: "General", keywords: [] },
    { label: "My Attendance", path: "/hr/MyAttendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "Settings", path: "/hr/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/hr/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
  Finance: [
    { label: "Home", path: "/finance", category: "General", keywords: [] },
    { label: "Finance / Analytics", path: "/finance/finance-analytics", category: "Finance", keywords: ["revenue"] },
    { label: "Finance / Analytics", subLabel: "Student Analytics", path: "/finance/finance-analytics/students", category: "Finance", keywords: ["student fees", "dues", "collection"] },
    { label: "Add Fee Structure", path: "/finance/add-fee-structure", category: "Finance", keywords: ["create fees", "tuition", "pricing"] },
    { label: "Calendar", path: "/finance/calendar", category: "General", keywords: [] },
    { label: "Drive", path: "/finance/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", path: "/finance/meetings", category: "General", keywords: [] },
    { label: "My Attendance", path: "/finance/my-attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "Settings", path: "/finance/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/finance/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
  PlacementOfficer: [
    { label: "Home", path: "/placement", category: "General", keywords: [] },
    { label: "Calendar", path: "/placement/calendar", category: "General", keywords: [] },
    { label: "Attendance", path: "/placement/attendance", category: "Academics", keywords: [] },
    { label: "Placements", path: "/placement/placements", category: "Career", keywords: ["jobs", "interviews", "companies", "drives", "recruitment"] },
    { label: "Meetings", path: "/placement/meetings", category: "General", keywords: [] },
    { label: "Drive", path: "/placement/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "My Attendance", path: "/placement/my-attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "Settings", path: "/placement/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/placement/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
  Parent: [
    { label: "Home", path: "/parent", category: "General", keywords: [] },
    { label: "Attendance", path: "/parent/attendance", category: "Academics", keywords: [] },
    { label: "Student Progress", path: "/parent/student-progress", category: "Academics", keywords: [] },
    { label: "Meetings", path: "/parent/meetings", category: "General", keywords: [] },
    { label: "Settings", path: "/parent/settings", category: "Account", keywords: [] },
    { label: "Settings", subLabel: "Change Password", path: "/parent/settings?current-password", category: "Account", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
  SuperAdmin: [
    { label: "Home", path: "/super-admin", category: "General", keywords: [] },
    { label: "Registration", path: "/super-admin/registration", category: "Management", keywords: ["new college", "create"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Account", keywords: ["profile", "photo"] },
  ],
};

export const getSearchRoutesByRole = (role?: string | null): SearchRoute[] => {
  if (!role || !ROLE_BASED_ROUTES[role]) return [];
  return ROLE_BASED_ROUTES[role];
};