export interface SearchRoute {
  label: string;
  path: string;
  category: string;
  subLabel?: string;
  keywords?: string[];
}

export const ROLE_BASED_ROUTES: Record<string, SearchRoute[]> = {
  Student: [
    { label: "Home", path: "/stu_dashboard", category: "Dashboard", keywords: [] },
    { label: "Calendar", path: "/calendar", category: "Academics", keywords: ["timetable"] },
    { label: "Attendance", subLabel: "Today's Attendance", path: "/attendance", category: "Academics", keywords: ["today attendance"] },
    { label: "Attendance", subLabel: "Subject-Wise Attendance", path: "/attendance?tab=subject-attendance", category: "Academics", keywords: ["subject wise attendance"] },
    { label: "Assignment", subLabel: "Assignments / Quiz / Discussion Forum", path: "/assignments", category: "Academics", keywords: [] },
    { label: "Quiz", subLabel: "Assignments / Quiz / Discussion Forum", path: "/assignments?tab=quiz&quizView=ongoing", category: "Academics", keywords: ["quiz"] },
    { label: "Discussion Forum", subLabel: "Assignments / Quiz / Discussion Forum", path: "/assignments?tab=discussion&quizView=ongoing&discussionView=active", category: "Academics", keywords: ["discussion", "forum"] },
    { label: "Academics", path: "/academics", category: "Academics", keywords: [] },
    { label: "Student Progress", path: "/student-progress", category: "Academics", keywords: [] },
    { label: "Projects", path: "/projects", category: "Academics", keywords: [] },
    { label: "Placements", path: "/stu_placements", category: "Career", keywords: ["jobs", "interviews"] },
    { label: "Leave Requests", path: "/leaveRequests", category: "Requests", keywords: ["leave", "permission"] },
    { label: "Payments", path: "/payments", category: "Finance", keywords: ["fees", "dues", "receipts"] },
    { label: "Club", subLabel: "My Club", path: "/clubs?tab=myclub", category: "Extracurricular", keywords: ["activities", "my club"] },
    { label: "Club", subLabel: "All Clubs", path: "/clubs?tab=all", category: "Extracurricular", keywords: ["activities", "clubs", "all clubs"] },
    { label: "Drive", path: "/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", subLabel: "Upcoming Meetings", path: "/meetings?type=upcoming", category: "Collaboration", keywords: ["upcoming meetings", "new meetings"] },
    { label: "Meetings", subLabel: "Previous Meetings", path: "/meetings?type=previous", category: "Collaboration", keywords: ["previous meetings", "old meetings"] },
    { label: "Settings", path: "/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo",] },
    { label: "Resume", path: "/profile?resume=personal-details&Step=1", category: "Career Development", keywords: ["resume", "cv",] },
  ],
  Faculty: [
    { label: "Home", path: "/faculty", category: "Dashboard", keywords: [] },
    { label: "Calendar", path: "/faculty/calendar", category: "Academics", keywords: ["timetable"] },
    { label: "Attendance", path: "/faculty/attendance", category: "Academics", keywords: [] },
    { label: "Assignment", subLabel: "Assignments / Quiz / Discussion Forum", path: "/faculty/assignments", category: "Academics", keywords: [] },
    { label: "Quiz", subLabel: "Assignments / Quiz / Discussion Forum", path: "/faculty/assignments?tab=quiz&quizView=ongoing", category: "Academics", keywords: ["quiz"] },
    { label: "Discussion Forum", subLabel: "Assignments / Quiz / Discussion Forum", path: "/faculty/assignments?tab=discussion&quizView=ongoing&discussionView=active", category: "Academics", keywords: ["discussion", "forum"] },
    { label: "Academics", path: "/faculty/academics", category: "Academics", keywords: [] },
    { label: "Student Progress", path: "/faculty/student-progress", category: "Academics", keywords: [] },
    { label: "Projects", path: "/faculty/projects", category: "Academics", keywords: [] },
    { label: "Placements", path: "/faculty/placements", category: "Career", keywords: ["jobs", "interviews"] },
    { label: "Leave Requests", path: "/faculty/leaveRequests", category: "Requests", keywords: ["permission",] },
    { label: "Club", subLabel: "Requests", path: "/faculty/clubs?tab=requests", category: "Extracurricular", keywords: ["activities", "requests", "club requests"] },
    { label: "Club", subLabel: "Announcements", path: "/faculty/clubs?tab=announcements", category: "Extracurricular", keywords: ["activities", "announcements"] },
    { label: "Drive", path: "/faculty/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", subLabel: "Upcoming Meetings", path: "/faculty/meetings?type=upcoming", category: "Collaboration", keywords: ["upcoming meetings", "new meetings"] },
    { label: "Meetings", subLabel: "Previous Meetings", path: "/faculty/meetings?type=previous", category: "Collaboration", keywords: ["previous meetings", "old meetings"] },
    { label: "My Attendance", path: "/faculty/my-attendance?main=attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "My Attendance", subLabel: "Payroll", path: "/faculty/my-attendance?main=payroll&sub=summary", category: "Finance", keywords: ["payroll"] },
    { label: "Settings", path: "/faculty/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/faculty/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/faculty/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/faculty/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/faculty/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/faculty/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
  Admin: [
    { label: "Home", path: "/admin", category: "Dashboard", keywords: [] },
    { label: "Home", subLabel: "Total Users", path: "/admin?view=TOTAL_USERS", category: "Dashboard", keywords: ["total users"] },
    { label: "Calendar", path: "/admin/calendar", category: "Academics", keywords: ["timetable"] },
    { label: "Attendance", path: "/admin/attendance", category: "Academics", keywords: [] },
    { label: "Assignment", subLabel: "Assignments / Quiz / Discussion Forum", path: "/admin/assignments", category: "Academics", keywords: [] },
    { label: "Quiz", subLabel: "Assignments / Quiz / Discussion Forum", path: "/admin/assignments?tab=quiz&quizView=ongoing", category: "Academics", keywords: ["quiz"] },
    { label: "Discussion Forum", subLabel: "Assignments / Quiz / Discussion Forum", path: "/admin/assignments?tab=discussion&quizView=ongoing&discussionView=active", category: "Academics", keywords: ["discussion", "forum"] },
    { label: "Academics", path: "/admin/academics", category: "Academics", keywords: ["curriculum"] },
    { label: "Student Progress", path: "/admin/student-progress", category: "Academics", keywords: ["performance", "reports", "analytics"] },
    { label: "Projects", path: "/admin/projects", category: "Academics", keywords: [] },
    { label: "Academic Setup", path: "/admin/academic-setup", category: "Academics", keywords: ["configuration", "structure", "courses"] },
    { label: "Academic Setup", subLabel: "Add Subject", path: "/admin/academic-setup?", category: "Academics", keywords: ["add subject", "subject add"] },
    { label: "Placements", path: "/admin/placements", category: "Career", keywords: ["drives", "companies"] },
    { label: "Club", subLabel: "View Clubs", path: "/admin/clubs?tab=view", category: "Extracurricular", keywords: ["organizations", "view clubs"] },
    { label: "Club", subLabel: "Add New Club", path: "/admin/clubs?tab=add", category: "Extracurricular", keywords: ["organizations", "add new club", "add club"] },
    { label: "Drive", path: "/admin/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", subLabel: "Upcoming Meetings", path: "/admin/meetings?type=upcoming", category: "Collaboration", keywords: ["upcoming meetings", "new meetings"] },
    { label: "Meetings", subLabel: "Previous Meetings", path: "/admin/meetings?type=previous", category: "Collaboration", keywords: ["previous meetings", "old meetings"] },
    { label: "My Attendance", path: "/admin/my-attendance?main=attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "My Attendance", subLabel: "Payroll", path: "/admin/my-attendance?main=payroll&sub=summary", category: "Finance", keywords: ["payroll"] },
    { label: "Settings", path: "/admin/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/admin/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/admin/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/admin/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/admin/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/admin/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
  CollegeAdmin: [
    { label: "Home", path: "/college-admin", category: "Dashboard", keywords: [] },
    { label: "Institution Management", path: "/college-admin/institution-management", category: "Management", keywords: ["manage", "organization"] },
    { label: "Add Admin", path: "/college-admin/add-admin", category: "Management", keywords: ["new admin", "register", "create admin"] },
    { label: "Calendar", path: "/college-admin/calendar", category: "Academics", keywords: [] },
    { label: "Drive", path: "/college-admin/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "My Attendance", path: "/college-admin/my-attendance?main=attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "My Attendance", subLabel: "Payroll", path: "/college-admin/my-attendance?main=payroll&sub=summary", category: "Finance", keywords: ["payroll"] },
    { label: "Settings", path: "/college-admin/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/college-admin/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/college-admin/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/college-admin/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/college-admin/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/college-admin/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
  CollegeHr: [
    { label: "Home", path: "/hr", category: "Dashboard", keywords: [] },
    { label: "Calendar", path: "/hr/calendar", category: "Academics", keywords: [] },
    { label: "Attendance", path: "/hr/attendance", category: "Management", keywords: ["staff attendance"] },
    { label: "Drive", path: "/hr/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", subLabel: "Upcoming Meetings", path: "/hr/meetings?type=upcoming", category: "Collaboration", keywords: ["upcoming meetings", "new meetings"] },
    { label: "Meetings", subLabel: "Previous Meetings", path: "/hr/meetings?type=previous", category: "Collaboration", keywords: ["previous meetings", "old meetings"] },
    { label: "My Attendance", path: "/hr/MyAttendance?main=attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "My Attendance", subLabel: "Payroll", path: "/hr/MyAttendance?main=payroll&sub=summary", category: "Finance", keywords: ["payroll"] },
    { label: "Settings", path: "/hr/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/hr/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/hr/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/hr/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/hr/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/hr/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
  Finance: [
    { label: "Home", path: "/finance", category: "Dashboard", keywords: [] },
    { label: "Payment Reminder", path: "/finance?view=PaymentReminder", category: "Finance", keywords: ["reminder", "payment reminder"] },
    { label: "Finance / Analytics", path: "/finance/finance-analytics", category: "Finance", keywords: ["revenue"] },
    { label: "Finance / Analytics", subLabel: "Student Analytics", path: "/finance/finance-analytics/students", category: "Finance", keywords: ["student fees", "dues", "collection"] },
    { label: "Add Fee Structure", path: "/finance/add-fee-structure", category: "Finance", keywords: ["create fees", "tuition", "pricing"] },
    { label: "Calendar", path: "/finance/calendar", category: "Academics", keywords: [] },
    { label: "Drive", path: "/finance/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "Meetings", subLabel: "Upcoming Meetings", path: "/finance/meetings?type=upcoming", category: "Collaboration", keywords: ["upcoming meetings", "new meetings"] },
    { label: "Meetings", subLabel: "Previous Meetings", path: "/finance/meetings?type=previous", category: "Collaboration", keywords: ["previous meetings", "old meetings"] },
    { label: "My Attendance", path: "/finance/my-attendance?main=attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "My Attendance", subLabel: "Payroll", path: "/finance/my-attendance?main=payroll&sub=summary", category: "Finance", keywords: ["payroll"] },
    { label: "Settings", path: "/finance/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/finance/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/finance/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/finance/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/finance/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/finance/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
  PlacementOfficer: [
    { label: "Home", path: "/placement", category: "Dashboard", keywords: [] },
    { label: "Calendar", path: "/placement/calendar", category: "Academics", keywords: [] },
    { label: "Attendance", path: "/placement/attendance", category: "Academics", keywords: [] },
    { label: "Placements", subLabel: "Company Management", path: "/placement/placements?tab=company-management", category: "Career", keywords: ["management", "company management"] },
    { label: "Placements", subLabel: "Placement Drives", path: "/placement/placements?tab=placement-drives", category: "Career", keywords: ["jobs", "interviews", "companies", "drives", "recruitment"] },
    { label: "Placements", subLabel: "Results & Offers", path: "/placement/placements?tab=results-offers", category: "Career", keywords: ["results and offers", "results", "offers"] },
    { label: "Meetings", path: "/placement/meetings", category: "Collaboration", keywords: [] },
    { label: "Drive", path: "/placement/drive", category: "Resources", keywords: ["files", "documents", "storage"] },
    { label: "My Attendance", path: "/placement/my-attendance?main=attendance", category: "Academics", keywords: ["personal attendance"] },
    { label: "My Attendance", subLabel: "Payroll", path: "/placement/my-attendance?main=payroll&sub=summary", category: "Finance", keywords: ["payroll"] },
    { label: "Settings", path: "/placement/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/placement/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/placement/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/placement/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/placement/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/placement/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
  Parent: [
    { label: "Home", path: "/parent", category: "Dashboard", keywords: [] },
    { label: "Payments", subLabel: "Academic Fees / Additional Dues / History", path: "/parent/payments", category: "Finance", keywords: ["payments", "academic fees", "additional dues", "history"] },
    { label: "Attendance", subLabel: "Today's Attendance", path: "/parent/attendance", category: "Academics", keywords: [] },
    { label: "Attendance", subLabel: "Subject-Wise Attendance", path: "/parent/attendance?tab=subject-attendance", category: "Academics", keywords: [] },
    { label: "Student Progress", path: "/parent/student-progress", category: "Academics", keywords: [] },
    { label: "Meetings", subLabel: "Upcoming Meetings", path: "/parent/meetings?type=upcoming", category: "Collaboration", keywords: ["upcoming meetings", "new meetings"] },
    { label: "Meetings", subLabel: "Previous Meetings", path: "/parent/meetings?type=previous", category: "Collaboration", keywords: ["previous meetings", "old meetings"] },
    { label: "Settings", path: "/parent/settings", category: "Preferences", keywords: [] },
    { label: "Settings", subLabel: "Privacy Policy", path: "/parent/settings?privacy-policy", category: "Legal", keywords: ["privacy policy", "policy"] },
    { label: "Settings", subLabel: "Trusted Devices List", path: "/parent/settings?trusted-devices", category: "Security", keywords: ["devices list", "trusted devices"] },
    { label: "Settings", subLabel: "Two-Step Verification", path: "/parent/settings?2fa", category: "Security", keywords: ["verification", "twostep", "two-step verification"] },
    { label: "Settings", subLabel: "Linked Accounts", path: "/parent/settings?linked-accounts", category: "Security", keywords: ["linked accounts", "manage accounts"] },
    { label: "Settings", subLabel: "Change Password", path: "/parent/settings?current-password", category: "Security", keywords: ["password", "update password", "change password"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
  SuperAdmin: [
    { label: "Home", path: "/super-admin", category: "Dashboard", keywords: [] },
    { label: "Registration", subLabel: "College / Admin / Educational Type / Departments", path: "/super-admin/registration", category: "Management", keywords: ["new college", "create", "new admin", "add admin", "educational type", "departments"] },
    { label: "Profile", path: "/profile?profile=profile&Step=1", category: "Personal", keywords: ["profile", "photo"] },
  ],
};

export const SHARED_ACTION_ROUTES: SearchRoute[] = [
  { label: "Notifications", path: "action:notifications", category: "Quick Actions", keywords: ["alerts", "updates", "bell"] },
  { label: "News", path: "action:news", category: "Quick Actions", keywords: ["daily news", "articles", "newspaper"] },
  // { label: "Email", path: "action:email", category: "Quick Actions", keywords: ["inbox", "messages", "mail"] },
  { label: "Email", subLabel: "Inbox", path: "action:email:inbox", category: "Quick Actions", keywords: ["inbox", "messages", "mail", "received"] },
  { label: "Email", subLabel: "Sent Mails", path: "action:email:sent", category: "Quick Actions", keywords: ["sent mails", "outbox", "delivered"] },
  { label: "Email", subLabel: "Compose New", path: "action:email:compose", category: "Quick Actions", keywords: ["compose", "new mail", "send mail", "write", "create"] },
  { label: "Campus Buzz", path: "action:announcement", category: "Quick Actions", keywords: ["announcements", "megaphone", "buzz", "campus buzz"] },
];

export const getSearchRoutesByRole = (role?: string | null): SearchRoute[] => {
  if (!role || !ROLE_BASED_ROUTES[role]) return [];
  // return ROLE_BASED_ROUTES[role];
  return [...ROLE_BASED_ROUTES[role], ...SHARED_ACTION_ROUTES];
};