export const foldersMock = [
  {
    id: 1,
    name: "Assignments",
    filesCount: 23,
    sizeLabel: "137 MB",
    color: "#0BA968",
  },
  {
    id: 2,
    name: "Notes",
    filesCount: 26,
    sizeLabel: "137 MB",
    color: "#FF8A3C",
  },
  {
    id: 3,
    name: "Projects",
    filesCount: 9,
    sizeLabel: "137 MB",
    color: "#265DAB",
  },
  {
    id: 4,
    name: "Question Papers",
    filesCount: 13,
    sizeLabel: "137 MB",
    color: "#9C6ADE",
  },
  {
    id: 5,
    name: "Presentations",
    filesCount: 18,
    sizeLabel: "137 MB",
    color: "#EF5DA8",
  },
  {
    id: 6,
    name: "Homework",
    filesCount: 23,
    sizeLabel: "137 MB",
    color: "#0BA968",
  },
];

export const recentFilesMock = [
  {
    id: 1,
    name: "DSA_Lab_Experiment_4.pdf",
    type: "PDF",
    sizeLabel: "1.0 MB",
    uploadedOnLabel: "11/05/2025",
    uploadedOn: "2025-05-11",
  },
  {
    id: 2,
    name: "WebTech_Project_Report.pdf",
    type: "PDF",
    sizeLabel: "1.0 MB",
    uploadedOnLabel: "11/05/2025",
    uploadedOn: "2025-05-11",
  },
  {
    id: 3,
    name: "WebTech_Project_Report_Final.pdf",
    type: "PDF",
    sizeLabel: "1.0 MB",
    uploadedOnLabel: "11/05/2025",
    uploadedOn: "2025-05-11",
  },
  {
    id: 4,
    name: "OS_Notes_Unit_3.pdf",
    type: "PDF",
    sizeLabel: "1.0 MB",
    uploadedOnLabel: "11/05/2025",
    uploadedOn: "2025-05-11",
  },
  {
    id: 5,
    name: "Computer_Networks_4.pdf",
    type: "PDF",
    sizeLabel: "2.0 MB",
    uploadedOnLabel: "11/05/2025",
    uploadedOn: "2025-05-11",
  },
];

export const allFilesMock = [
  {
    id: 1,
    name: "DSA_Lab_Experiment_4.pdf",
    type: "PDF",
    sizeLabel: "2.3 MB",
    sizeMb: 2.3,
    uploadedOnLabel: "05 Nov 2025",
    uploadedOn: "2025-11-05",
  },
  {
    id: 2,
    name: "WebTech_Lab_Report.pdf",
    type: "PDF",
    sizeLabel: "2.3 MB",
    sizeMb: 2.3,
    uploadedOnLabel: "05 Nov 2025",
    uploadedOn: "2025-11-05",
  },
  {
    id: 3,
    name: "Project_Proposal.pptx",
    type: "PPTX",
    sizeLabel: "2.3 MB",
    sizeMb: 2.3,
    uploadedOnLabel: "05 Nov 2025",
    uploadedOn: "2025-11-05",
  },
  {
    id: 4,
    name: "Database_ER_Diagram.png",
    type: "PNG",
    sizeLabel: "2.3 MB",
    sizeMb: 2.3,
    uploadedOnLabel: "05 Nov 2025",
    uploadedOn: "2025-11-05",
  },
  {
    id: 5,
    name: "Java_Practice_Programs.zip",
    type: "ZIP",
    sizeLabel: "2.3 MB",
    sizeMb: 2.3,
    uploadedOnLabel: "05 Nov 2025",
    uploadedOn: "2025-11-05",
  },
  {
    id: 6,
    name: "CN_Lab_Output.docx",
    type: "DOCX",
    sizeLabel: "2.3 MB",
    sizeMb: 2.3,
    uploadedOnLabel: "05 Nov 2025",
    uploadedOn: "2025-11-05",
  },
  {
    id: 7,
    name: "Resume_CSE_Student.pdf",
    type: "PDF",
    sizeLabel: "2.3 MB",
    sizeMb: 2.3,
    uploadedOnLabel: "05 Nov 2025",
    uploadedOn: "2025-11-05",
  },
];
