import { Meeting } from "../page";

export const MOCK_MEETINGS: Meeting[] = [

  // =====================================================
  // 🔹 PARENT - UPCOMING (8 ITEMS)
  // =====================================================
  {
    id: 'p-u-1',
    title: 'Fee Structure Discussion',
    timeRange: '8:00 AM - 9:00 AM',
    educationType: 'B.Tech',
    date: '20 Feb 2026',
    participants: 20,
    year: '2nd Year',
    section: 'A',
    tags: 'CSE',
    category: 'parent',
    type: 'upcoming',
  },
  {
    id: 'p-u-2',
    title: 'Scholarship Awareness',
    timeRange: '9:00 AM - 10:00 AM',
    educationType: 'B.Tech',
    date: '21 Feb 2026',
    participants: 35,
    year: '1st Year',
    section: 'B',
    tags: 'EEE',
    category: 'parent',
    type: 'upcoming',
  },
  {
    id: 'p-u-3',
    title: 'Hostel Discussion',
    timeRange: '10:00 AM - 11:00 AM',
    educationType: 'B.Tech',
    date: '22 Feb 2026',
    participants: 25,
    year: '3rd Year',
    section: 'A',
    tags: 'MECH',
    category: 'parent',
    type: 'upcoming',
  },
  {
    id: 'p-u-4',
    title: 'Transport Facility Review',
    timeRange: '11:00 AM - 12:00 PM',
    educationType: 'B.Tech',
    date: '23 Feb 2026',
    participants: 30,
    year: 'All',
    section: 'All',
    tags: 'CIVIL',
    category: 'parent',
    type: 'upcoming',
  },
  {
    id: 'p-u-5',
    title: 'Academic Progress Meeting',
    timeRange: '1:00 PM - 2:00 PM',
    educationType: 'B.Tech',
    date: '24 Feb 2026',
    participants: 18,
    year: '2nd Year',
    section: 'C',
    tags: 'CSE',
    category: 'parent',
    type: 'upcoming',
  },
  {
    id: 'p-u-6',
    title: 'Attendance Review',
    timeRange: '2:00 PM - 3:00 PM',
    educationType: 'B.Tech',
    date: '25 Feb 2026',
    participants: 22,
    year: '1st Year',
    section: 'A',
    tags: 'EEE',
    category: 'parent',
    type: 'upcoming',
  },
  {
    id: 'p-u-7',
    title: 'Lab Infrastructure Discussion',
    timeRange: '3:00 PM - 4:00 PM',
    educationType: 'B.Tech',
    date: '26 Feb 2026',
    participants: 15,
    year: '3rd Year',
    section: 'B',
    tags: 'MECH',
    category: 'parent',
    type: 'upcoming',
  },
  {
    id: 'p-u-8',
    title: 'Exam Preparation Strategy',
    timeRange: '4:00 PM - 5:00 PM',
    educationType: 'B.Tech',
    date: '27 Feb 2026',
    participants: 28,
    year: '4th Year',
    section: 'All',
    tags: 'CSE',
    category: 'parent',
    type: 'upcoming',
  },

  // =====================================================
  // 🔹 PARENT - PREVIOUS (6 ITEMS)
  // =====================================================
  {
    id: 'p-pr-1',
    title: 'Annual Fee Review',
    timeRange: '8:00 AM - 9:00 AM',
    educationType: 'B.Tech',
    date: '10 Jan 2026',
    participants: 40,
    year: '4th Year',
    section: 'All',
    tags: 'CSE',
    category: 'parent',
    type: 'previous',
  },
  {
    id: 'p-pr-2',
    title: 'Exam Fee Clarification',
    timeRange: '9:00 AM - 10:00 AM',
    educationType: 'B.Tech',
    date: '15 Jan 2026',
    participants: 18,
    year: '2nd Year',
    section: 'C',
    tags: 'CIVIL',
    category: 'parent',
    type: 'previous',
  },
  {
    id: 'p-pr-3',
    title: 'Curriculum Feedback Session',
    timeRange: '10:00 AM - 11:00 AM',
    educationType: 'B.Tech',
    date: '18 Jan 2026',
    participants: 22,
    year: '3rd Year',
    section: 'A',
    tags: 'EEE',
    category: 'parent',
    type: 'previous',
  },
  {
    id: 'p-pr-4',
    title: 'Library Access Discussion',
    timeRange: '11:00 AM - 12:00 PM',
    educationType: 'B.Tech',
    date: '20 Jan 2026',
    participants: 14,
    year: '1st Year',
    section: 'B',
    tags: 'MECH',
    category: 'parent',
    type: 'previous',
  },
  {
    id: 'p-pr-5',
    title: 'Transport Committee Review',
    timeRange: '1:00 PM - 2:00 PM',
    educationType: 'B.Tech',
    date: '22 Jan 2026',
    participants: 19,
    year: 'All',
    section: 'All',
    tags: 'CSE',
    category: 'parent',
    type: 'previous',
  },
  {
    id: 'p-pr-6',
    title: 'Safety & Security Review',
    timeRange: '2:00 PM - 3:00 PM',
    educationType: 'B.Tech',
    date: '25 Jan 2026',
    participants: 16,
    year: 'All',
    section: 'All',
    tags: 'CIVIL',
    category: 'parent',
    type: 'previous',
  },

  // =====================================================
  // 🔹 STUDENT (6 UPCOMING + 6 PREVIOUS)
  // =====================================================
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `s-u-${i + 1}`,
    title: `Student Upcoming Meeting ${i + 1}`,
    timeRange: '11:00 AM - 12:00 PM',
    educationType: 'B.Tech',
    date: `0${i + 1} Mar 2026`,
    participants: 80 + i * 5,
    year: 'All',
    section: 'All',
    tags: 'CSE',
    category: 'student' as const,
    type: 'upcoming' as const,
  })),
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `s-pr-${i + 1}`,
    title: `Student Previous Meeting ${i + 1}`,
    timeRange: '2:00 PM - 3:00 PM',
    educationType: 'B.Tech',
    date: `1${i + 1} Jan 2026`,
    participants: 60 + i * 4,
    year: 'All',
    section: 'All',
    tags: 'EEE',
    category: 'student' as const,
    type: 'previous' as const,
  })),

  // =====================================================
  // 🔹 FACULTY (6 + 6)
  // =====================================================
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `f-u-${i + 1}`,
    title: `Faculty Planning Session ${i + 1}`,
    timeRange: '10:00 AM - 11:00 AM',
    educationType: 'B.Tech',
    date: `1${i + 1} Mar 2026`,
    participants: 15 + i,
    year: 'All',
    section: 'All',
    tags: 'MECH',
    category: 'faculty' as const,
    type: 'upcoming' as const,
  })),
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `f-pr-${i + 1}`,
    title: `Faculty Review Meeting ${i + 1}`,
    timeRange: '3:00 PM - 4:00 PM',
    educationType: 'B.Tech',
    date: `0${i + 1} Jan 2026`,
    participants: 10 + i,
    year: 'All',
    section: 'All',
    tags: 'CIVIL',
    category: 'faculty' as const,
    type: 'previous' as const,
  })),

  // =====================================================
  // 🔹 ADMIN (6 + 6)
  // =====================================================
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `a-u-${i + 1}`,
    title: `Admin Planning Meeting ${i + 1}`,
    timeRange: '4:00 PM - 5:00 PM',
    educationType: 'B.Tech',
    date: `2${i + 1} Mar 2026`,
    participants: 5 + i,
    year: 'All',
    section: 'All',
    tags: 'ADMIN',
    category: 'admin' as const,
    type: 'upcoming' as const,
  })),
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `a-pr-${i + 1}`,
    title: `Admin Review Session ${i + 1}`,
    timeRange: '1:00 PM - 2:00 PM',
    educationType: 'B.Tech',
    date: `2${i + 1} Jan 2026`,
    participants: 4 + i,
    year: 'All',
    section: 'All',
    tags: 'ADMIN',
    category: 'admin' as const,
    type: 'previous' as const,
  })),
];
