create table if not exists public.college_exam_schedule_sections (
  "collegeExamScheduleSectionId" bigint generated by default as identity primary key,
  "collegeExamScheduleId" bigint not null references public.college_exam_schedules("collegeExamScheduleId") on delete cascade,
  "collegeSectionsId" bigint not null references public.college_sections("collegeSectionsId") on delete cascade,
  "createdAt" timestamptz not null default now(),
  unique ("collegeExamScheduleId", "collegeSectionsId")
);

create index if not exists college_exam_schedule_sections_schedule_idx
  on public.college_exam_schedule_sections ("collegeExamScheduleId");

create index if not exists college_exam_schedule_sections_section_idx
  on public.college_exam_schedule_sections ("collegeSectionsId");
