import type { CalendarEvent } from "./types";

export const TIME_SLOTS = [
  "08:00 AM",
  "09:00 AM",
  "10:00 AM",
  "11:00 AM",
  "12:00 PM",
  "01:00 PM",
  "02:00 PM",
  "03:00 PM",
  "04:00 PM",
  "05:00 PM",
  "06:00 PM",
  "07:00 PM",
  "08:00 PM",
  "09:00 PM",
];

export const CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "1",
    dayIndex: 0,
    startHour: 9,
    duration: 1.5,
    time: "9:00 AM - 10:30 AM",
    title: "Principles of Design",
    topic: "Design principles",
    participants: "Wellbeing Team",
    type: "class",
    branch: "Design",
    year: "2nd Year",
    section: "Sec-A",
  },
  {
    id: "2",
    dayIndex: 0,
    startHour: 11,
    duration: 1,
    time: "10:00 AM - 11:00 AM",
    title: "Executive Sync - Daily Updates",
    topic: "Daily updates",
    participants: "Executives",
    type: "exam",
    branch: "Hostel",
    year: "Support",
    section: "Team",
  },
  {
    id: "3",
    dayIndex: 1,
    startHour: 9,
    duration: 1.1,
    time: "8:00 AM - 9:00 AM",
    title: "Executive Planning Meeting - Upcoming Programs",
    topic: "Upcoming programs",
    participants: "Executives",
    type: "class",
    branch: "Planning",
    year: "Executive",
    section: "Team",
  },
  {
    id: "4",
    dayIndex: 1,
    startHour: 11,
    duration: 1.15,
    time: "11:00 AM - 12:00 PM",
    title: "Case Review - Urgent Issues",
    topic: "Urgent issues",
    participants: "Support Team",
    type: "meeting",
    branch: "Case Review",
    year: "Urgent",
    section: "Issues",
  },
  {
    id: "5",
    dayIndex: 2,
    startHour: 8.15,
    duration: 1.1,
    time: "10:00 AM - 11:00 AM",
    title: "Team Meeting - Weekly Case Review",
    topic: "Weekly case review",
    participants: "Wellbeing Team",
    type: "exam",
    branch: "Weekly",
    year: "Case",
    section: "Review",
  },
  {
    id: "6",
    dayIndex: 2,
    startHour: 12,
    duration: 1.15,
    time: "10:00 AM - 11:00 AM",
    title: "Wellness Campaign Planning",
    topic: "Wellness campaign",
    participants: "Planning Team",
    type: "exam",
    branch: "Wellness",
    year: "Campaign",
    section: "Team",
  },
  {
    id: "7",
    dayIndex: 3,
    startHour: 10,
    duration: 1.1,
    time: "8:00 AM - 9:00 AM",
    title: "Emergency Executive Meeting",
    topic: "Emergency issue review",
    participants: "Executives",
    type: "exam",
    branch: "Emergency",
    year: "Executive",
    section: "Team",
  },
  {
    id: "8",
    dayIndex: 4,
    startHour: 8.55,
    duration: 1.1,
    time: "8:00 AM - 9:00 AM",
    title: "Staff Welfare Committee Meeting",
    topic: "Staff welfare committee",
    participants: "Committee",
    type: "class",
    branch: "Staff",
    year: "Welfare",
    section: "Committee",
  },
  {
    id: "9",
    dayIndex: 4,
    startHour: 11.35,
    duration: 1.1,
    time: "8:00 AM - 9:00 AM",
    title: "End-of-Month Attendance Audit",
    topic: "Attendance audit",
    participants: "Wellbeing Team",
    type: "meeting",
    branch: "Attendance",
    year: "Audit",
    section: "Team",
  },
];
