import { CourseCardData } from "./components/courseCard";

export const mockCourses: CourseCardData[] = [
  {
    id: 1,
    subject: "DATA STRUCTURES",
    instructorName: "Dr. Meena Reddy",
    instructorId: "89273648",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    activeAssignments: 4,
    pendingSubmissions: 4,
    issuesRaised: 2,
  },
  {
    id: 2,
    subject: "DISCRETE MATHEMATICS",
    instructorName: "Ananya Rao",
    instructorId: "89273648",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
    activeAssignments: 4,
    pendingSubmissions: 4,
    issuesRaised: 2,
  },
  {
    id: 3,
    subject: "OOPS USING JAVA",
    instructorName: "Nikhil Verma",
    instructorId: "89273648",
    avatarUrl: "https://i.pravatar.cc/150?img=13",
    activeAssignments: 4,
    pendingSubmissions: 4,
    issuesRaised: 2,
  },
  {
    id: 4,
    subject: "COMPUTER NETWORKS",
    instructorName: "Neha Singh",
    instructorId: "89273648",
    avatarUrl: "https://i.pravatar.cc/150?img=49",
    activeAssignments: 4,
    pendingSubmissions: 4,
    issuesRaised: 2,
  },
  {
    id: 5,
    subject: "DBMS",
    instructorName: "Rahul Anand",
    instructorId: "89273648",
    avatarUrl: "https://i.pravatar.cc/150?img=59",
    activeAssignments: 4,
    pendingSubmissions: 4,
    issuesRaised: 2,
  },
  {
    id: 6,
    subject: "OPERATING SYSTEMS",
    instructorName: "Priya Menon",
    instructorId: "89273648",
    avatarUrl: "https://i.pravatar.cc/150?img=45",
    activeAssignments: 4,
    pendingSubmissions: 4,
    issuesRaised: 2,
  },
];
